# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Few-Shot-Feature-Space',
                'doc_host': 'https://Irad-Zehavi.github.io',
                'git_url': 'https://github.com/Irad-Zehavi/Few-Shot-Feature-Space',
                'lib_path': 'Few_Shot_Feature_Space'},
  'syms': {'Few_Shot_Feature_Space.core': {'Few_Shot_Feature_Space.core.foo': ('core.html#foo', 'Few_Shot_Feature_Space/core.py')}}}
